
version: 2

models:
  - name: customers 
    description: "customer and convenient order information"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null